name: PHP Code Sniffer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  phpcs:
      name: PHPCS
      runs-on: ubuntu-latest
      steps:
        - uses: shivammathur/setup-php
          with:
            php-version: '8.0'
          uses: chekalsky/phpcs-action@v2
        - name: Install dependencies
          run: composer install --dev --prefer-dist --no-progress --no-suggest
        - name: PHPCS check
          uses: chekalsky/phpcs-action@v1
          with:
            installed_paths: '${{ github.workspace }}/vendor/phpcompatibility/php-compatibility'
